/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_ghrp_pgquery_PgQueryWrapper */

#ifndef _Included_dev_ghrp_pgquery_PgQueryWrapper
#define _Included_dev_ghrp_pgquery_PgQueryWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_ghrp_pgquery_PgQueryWrapper
 * Method:    parseSQL
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_ghrp_pgquery_PgQueryWrapper_parseSQL
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
